/*
@TargetNode='localhost'
@GeneratedBy=swp54907
@GenerationDate=05/13/2024 15:55:25
@GenerationHost=SWPVM-CTDO
*/

instance of MSFT_SecurityOption as $MSFT_SecurityOption1ref
{
Accounts_Guest_account_status = "Disabled";
 ModuleName = "SecurityPolicyDsc";
 ResourceID = "[SecurityOption]SecurityOptions";
 Accounts_Rename_administrator_account = "NotAdmin";
 ModuleVersion = "2.10.0.0";
 SourceInfo = "::8::9::SecurityOption";
 Name = "SecurityOption";
 ConfigurationName = "SecurityBaseline";
};
instance of MSFT_AccountPolicy as $MSFT_AccountPolicy1ref
{
Maximum_Password_Age = 42;
 ModuleName = "SecurityPolicyDsc";
 ResourceID = "[AccountPolicy]AccountPolicies";
 Minimum_Password_Age = 1;
 Enforce_password_history = 15;
 ModuleVersion = "2.10.0.0";
 SourceInfo = "::14::9::AccountPolicy";
 Password_must_meet_complexity_requirements = "Enabled";
 Store_passwords_using_reversible_encryption = "Disabled";
 Name = "PasswordPolicies";
 Minimum_Password_Length = 12;
 ConfigurationName = "SecurityBaseline";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="swp54907";

                        GenerationDate="05/13/2024 15:55:25";

                        GenerationHost="SWPVM-CTDO";

                        Name="SecurityBaseline";

                    };
